### ISSUE TITLE
Error: Failed to login

### ISSUE THREAD

**Issue by Hello-World-Traveler** [fredrikburmester/streamystats#247]
Logged in successfully however the login page doesn't redirect. Stuck on login page.
```
 ⨯ Error: Failed to login

    at i (.next/server/app/(app)/servers/[id]/login/page.js:2:12774)

    at async o (.next/server/app/(app)/servers/[id]/login/page.js:1:18874)

    at async q (.next/server/app/(app)/servers/[id]/login/page.js:2:2715)

    at async N (.next/server/app/(app)/servers/[id]/login/page.js:2:7930) {

  digest: '635669578'
```

latest (128bb6c)

**Comment by fredrikburmester** [comment]
Can you try in a fresh browser, incognito mode? Thanks.

**Comment by fredrikburmester** [comment]
Are you using Streamystats locally or via a proxy (https domain)?

**Comment by Hello-World-Traveler** [comment]
Already tried that and different browser.

```
No active servers found for activity sync

No active servers found for recently added items sync

No active servers found for user sync
```
Local installed. I have also changed job server URL to IP address

**Comment by fredrikburmester** [comment]
Hmm those errors are different. Did you just set this up or did you just update?

**Comment by fredrikburmester** [comment]
Why did you change the job server IP?

**Comment by Hello-World-Traveler** [comment]
Updated 10 minutes. Had a connection issue https://github.com/fredrikburmester/streamystats/issues/215

**Comment by Hello-World-Traveler** [comment]
Changed it back to  http://job-server:3005, still unable to get pass login page.

**Comment by fredrikburmester** [comment]
I don't quite follow. What is your current issue? What version were you on before? Are you using the [docker compose file](https://github.com/fredrikburmester/streamystats/blob/main/docker-compose.yml) exactly?

**Comment by Hello-World-Traveler** [comment]
After updating to 2.6.0 I am stuck on the login page.

No I didn't use the compose file the first time. I have now used compose and have made the issue worse. 

I will remove everything and start again.

**Comment by Hello-World-Traveler** [comment]
I was able to login in 2.5.0, updated with watchtower and no longer able to get pass the login page. I have also removed all containers and updated compose page with no luck. 

Logged in successfully message shows in the right hand conner but stays on login page.

Removed everything, started the containers using compose file.  Still same issue.

Database container:
```
 [1] LOG:  database system is ready to accept connections

[27] LOG:  checkpoint starting: time

 [27] LOG:  checkpoint complete: wrote 119 buffers (0.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=11.827 s, sync=0.009 s, total=11.845 s; sync files=15, longest=0.004 s, average=0.001 s; distance=676 kB, estimate=676 kB; lsn=29/6EC29300, redo lsn=29/6EC292A8
```
Job-server container:
```
🚀 Job server running on port 3005

📊 Health check: http://0.0.0.0:3005/health

🔧 API docs: http://0.0.0.0:3005/

⏰ Activity sync scheduler is running (*/5 * * * *)

📦 Recently added items sync scheduler is running (*/5 * * * *)

👥 User sync scheduler is running (*/5 * * * *)

🔄 Daily full sync scheduler is running (0 2 * * *)

🎯 Session poller is running (every 5 seconds)

Triggering periodic activity sync...

Triggering periodic recently added items sync...

Triggering periodic user sync...

No active servers found for activity sync

No active servers found for user sync

No active servers found for recently added items sync
```
streamystats-nextjs-app container 

```
   ▲ Next.js 16.0.8

   - Local:         http://localhost:3000

   - Network:       http://0.0.0.0:3000

 ✓ Starting...

 ✓ Ready in 60ms
```

Each container had a lot mote information before reinstalled with compose file. Not sure if it's all working now.

**Comment by fredrikburmester** [comment]
Have you added a server? It looks like the container can't reach the server? Have you changed API key on the server? Can you connect to the Jellyfin server separatly? Are you using local ip of connecting through proxy?

**Comment by Hello-World-Traveler** [comment]
It was working in 2.5.0, updated now not working. 

Yes there was a server added in 2.5.0. URL redirects me to /servers/1/login not server.
No API key changed. Jellyfin Server is online. Using IP address to login on the login page.

Error fetching servers: Error: Failed query: select "id", "name", "url", "api_key", "last_synced_playback_id", "local_address", "version", "product_name", "operating_system", "startup_wizard_completed", "auto_generate_embeddings", "embedding_provider", "embedding_base_url", "embedding_api_key", "embedding_model", "embedding_dimensions", "sync_status", "sync_progress", "sync_error", "last_sync_started", "last_sync_completed", "created_at", "updated_at" from "servers"

params: 

    at s.queryWithCache (.next/server/middleware.js:42:52788)

    at async (.next/server/middleware.js:12:24093)

    at async p (.next/server/middleware.js:12:29265)

    at async a3 (.next/server/middleware.js:12:65169)

    at async handler (.next/server/middleware.js:12:66732)

    at async (.next/server/middleware.js:12:16334)

    at async E (.next/server/middleware.js:12:15337) {

  query: 'select "id", "name", "url", "api_key", "last_synced_playback_id", "local_address", "version", "product_name", "operating_system", "startup_wizard_completed", "auto_generate_embeddings", "embedding_provider", "embedding_base_url", "embedding_api_key", "embedding_model", "embedding_dimensions", "sync_status", "sync_progress", "sync_error", "last_sync_started", "last_sync_completed", "created_at", "updated_at" from "servers"',

  params: [],

  [cause]: Error: relation "servers" does not exist

      at ak (.next/server/middleware.js:16:2339)

      at <unknown> (.next/server/middleware.js:16:3385)

      at Socket.aN (.next/server/middleware.js:16:3389) {

    severity_local: 'ERROR',

    severity: 'ERROR',

    code: '42P01',

    position: '417',

    file: 'parse_relation.c',

    line: '1449',

    routine: 'parserOpenTable'

  }

}

Error: Failed to fetch servers from database

    at p (.next/server/middleware.js:12:29359)

    at async a3 (.next/server/middleware.js:12:65169)

    at async handler (.next/server/middleware.js:12:66732)

    at async (.next/server/middleware.js:12:16334)

    at async E (.next/server/middleware.js:12:15337)
```

Error checking server connectivity: Error: Failed query: select "id", "name", "url", "api_key", "last_synced_playback_id", "local_address", "version", "product_name", "operating_system", "startup_wizard_completed", "auto_generate_embeddings", "embedding_provider", "embedding_base_url", "embedding_api_key", "embedding_model", "embedding_dimensions", "sync_status", "sync_progress", "sync_error", "last_sync_started", "last_sync_completed", "created_at", "updated_at" from "servers"

params: 

    at s.queryWithCache (.next/server/chunks/199.js:1:17780)

    at async (.next/server/chunks/199.js:19:15498)

    at async k (.next/server/chunks/2638.js:1:307)

    at async A (.next/server/app/api/check-connectivity/route.js:1:1966)

    at async k (.next/server/app/api/check-connectivity/route.js:1:5814)

    at async j (.next/server/app/api/check-connectivity/route.js:1:6823) {

  query: 'select "id", "name", "url", "api_key", "last_synced_playback_id", "local_address", "version", "product_name", "operating_system", "startup_wizard_completed", "auto_generate_embeddings", "embedding_provider", "embedding_base_url", "embedding_api_key", "embedding_model", "embedding_dimensions", "sync_status", "sync_progress", "sync_error", "last_sync_started", "last_sync_completed", "created_at", "updated_at" from "servers"',

  params: [],

  [cause]: Error: relation "servers" does not exist

      at ak (.next/server/chunks/199.js:6:2339)

      at <unknown> (.next/server/chunks/199.js:6:3385)

      at Socket.aN (.next/server/chunks/199.js:6:3389) {

    severity_local: 'ERROR',

    severity: 'ERROR',

    code: '42P01',

    position: '417',

    file: 'parse_relation.c',

    line: '1449',

    routine: 'parserOpenTable'

  }

}
```

Issue connecting to database now?

```

2025-12-11 22:01:01.834 UTC [157] ERROR:  relation "servers" does not exist at character 417

2025-12-11 22:01:01.834 UTC [157] STATEMENT:  select "id", "name", "url", "api_key", "last_synced_playback_id", "local_address", "version", "product_name", "operating_system", "startup_wizard_completed", "auto_generate_embeddings", "embedding_provider", "embedding_base_url", "embedding_api_key", "embedding_model", "embedding_dimensions", "sync_status", "sync_progress", "sync_error", "last_sync_started", "last_sync_completed", "created_at", "updated_at" from "servers"
```

Not able to add server because the URL only redirects to login again. The only issue I had was on login the login page would refresh not allowing me to get passed it. 

Changing the database URL

```
Failed to start server: error: password authentication failed for user "postgres"

    at /app/node_modules/pg-pool/index.js:45:11

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

    at async Db.executeSql (/app/node_modules/pg-boss/src/db.js:28:14)

    at async Contractor.isInstalled (/app/node_modules/pg-boss/src/contractor.js:32:20)

    at async Contractor.start (/app/node_modules/pg-boss/src/contractor.js:37:23)

    at async PgBoss.start (/app/node_modules/pg-boss/src/index.js:101:5)

    at async getJobQueue (/app/dist/jobs/queue.js:63:5)

    at async startServer (/app/dist/index.js:105:9) {

  length: 104,

  severity: 'FATAL',

  code: '28P01',

  detail: undefined,

  hint: undefined,

  position: undefined,

  internalPosition: undefined,

  internalQuery: undefined,

  where: undefined,

  schema: undefined,

  table: undefined,

  column: undefined,

  dataType: undefined,

  constraint: undefined,

  file: 'auth.c',

  line: '329',

  routine: 'auth_failed'

}
```
changed to Database container IP: 172.29.0.2
postgresql://postgres:postgres@172.29.0.2:5432/streamystats

After all that, still can not login

**Comment by Hello-World-Traveler** [comment]
created a new volume for database

[create-server] Testing connection to server: http://IP:Port

[create-server] Checking for existing server with URL: http://IP:Port

Starting sequential sync for server ID: 1

Still unable to get pass login screen

**Comment by Ciechom** [comment]
> It was working in 2.5.0, updated now not working.
> 
> Yes there was a server added in 2.5.0. URL redirects me to /servers/1/login not server. No API key changed. Jellyfin Server is online. Using IP address to login on the login page.
> 
> Error fetching servers: Error: Failed query: select "id", "name", "url", "api_key", "last_synced_playback_id", "local_address", "version", "product_name", "operating_system", "startup_wizard_completed", "auto_generate_embeddings", "embedding_provider", "embedding_base_url", "embedding_api_key", "embedding_model", "embedding_dimensions", "sync_status", "sync_progress", "sync_error", "last_sync_started", "last_sync_completed", "created_at", "updated_at" from "servers"
> 
> params:
> 
> ```
> at s.queryWithCache (.next/server/middleware.js:42:52788)
> 
> at async (.next/server/middleware.js:12:24093)
> 
> at async p (.next/server/middleware.js:12:29265)
> 
> at async a3 (.next/server/middleware.js:12:65169)
> 
> at async handler (.next/server/middleware.js:12:66732)
> 
> at async (.next/server/middleware.js:12:16334)
> 
> at async E (.next/server/middleware.js:12:15337) {
> ```
> 
> query: 'select "id", "name", "url", "api_key", "last_synced_playback_id", "local_address", "version", "product_name", "operating_system", "startup_wizard_completed", "auto_generate_embeddings", "embedding_provider", "embedding_base_url", "embedding_api_key", "embedding_model", "embedding_dimensions", "sync_status", "sync_progress", "sync_error", "last_sync_started", "last_sync_completed", "created_at", "updated_at" from "servers"',
> 
> params: [],
> 
> [cause]: Error: relation "servers" does not exist
> 
> ```
>   at ak (.next/server/middleware.js:16:2339)
> 
>   at <unknown> (.next/server/middleware.js:16:3385)
> 
>   at Socket.aN (.next/server/middleware.js:16:3389) {
> 
> severity_local: 'ERROR',
> 
> severity: 'ERROR',
> 
> code: '42P01',
> 
> position: '417',
> 
> file: 'parse_relation.c',
> 
> line: '1449',
> 
> routine: 'parserOpenTable'
> ```
> 
> }
> 
> }
> 
> Error: Failed to fetch servers from database
> 
> ```
> at p (.next/server/middleware.js:12:29359)
> 
> at async a3 (.next/server/middleware.js:12:65169)
> 
> at async handler (.next/server/middleware.js:12:66732)
> 
> at async (.next/server/middleware.js:12:16334)
> 
> at async E (.next/server/middleware.js:12:15337)
> ```
> 
>  ```
> 
> Error checking server connectivity: Error: Failed query: select "id", "name", "url", "api_key", "last_synced_playback_id", "local_address", "version", "product_name", "operating_system", "startup_wizard_completed", "auto_generate_embeddings", "embedding_provider", "embedding_base_url", "embedding_api_key", "embedding_model", "embedding_dimensions", "sync_status", "sync_progress", "sync_error", "last_sync_started", "last_sync_completed", "created_at", "updated_at" from "servers"
> 
> params: 
> 
>     at s.queryWithCache (.next/server/chunks/199.js:1:17780)
> 
>     at async (.next/server/chunks/199.js:19:15498)
> 
>     at async k (.next/server/chunks/2638.js:1:307)
> 
>     at async A (.next/server/app/api/check-connectivity/route.js:1:1966)
> 
>     at async k (.next/server/app/api/check-connectivity/route.js:1:5814)
> 
>     at async j (.next/server/app/api/check-connectivity/route.js:1:6823) {
> 
>   query: 'select "id", "name", "url", "api_key", "last_synced_playback_id", "local_address", "version", "product_name", "operating_system", "startup_wizard_completed", "auto_generate_embeddings", "embedding_provider", "embedding_base_url", "embedding_api_key", "embedding_model", "embedding_dimensions", "sync_status", "sync_progress", "sync_error", "last_sync_started", "last_sync_completed", "created_at", "updated_at" from "servers"',
> 
>   params: [],
> 
>   [cause]: Error: relation "servers" does not exist
> 
>       at ak (.next/server/chunks/199.js:6:2339)
> 
>       at <unknown> (.next/server/chunks/199.js:6:3385)
> 
>       at Socket.aN (.next/server/chunks/199.js:6:3389) {
> 
>     severity_local: 'ERROR',
> 
>     severity: 'ERROR',
> 
>     code: '42P01',
> 
>     position: '417',
> 
>     file: 'parse_relation.c',
> 
>     line: '1449',
> 
>     routine: 'parserOpenTable'
> 
>   }
> 
> }
> ```
> 
> Issue connecting to database now?
> 
> ```
> 
> 2025-12-11 22:01:01.834 UTC [157] ERROR:  relation "servers" does not exist at character 417
> 
> 2025-12-11 22:01:01.834 UTC [157] STATEMENT:  select "id", "name", "url", "api_key", "last_synced_playback_id", "local_address", "version", "product_name", "operating_system", "startup_wizard_completed", "auto_generate_embeddings", "embedding_provider", "embedding_base_url", "embedding_api_key", "embedding_model", "embedding_dimensions", "sync_status", "sync_progress", "sync_error", "last_sync_started", "last_sync_completed", "created_at", "updated_at" from "servers"
> ```
> 
> Not able to add server because the URL only redirects to login again. The only issue I had was on login the login page would refresh not allowing me to get passed it.
> 
> Changing the database URL
> 
> ```
> Failed to start server: error: password authentication failed for user "postgres"
> 
>     at /app/node_modules/pg-pool/index.js:45:11
> 
>     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
> 
>     at async Db.executeSql (/app/node_modules/pg-boss/src/db.js:28:14)
> 
>     at async Contractor.isInstalled (/app/node_modules/pg-boss/src/contractor.js:32:20)
> 
>     at async Contractor.start (/app/node_modules/pg-boss/src/contractor.js:37:23)
> 
>     at async PgBoss.start (/app/node_modules/pg-boss/src/index.js:101:5)
> 
>     at async getJobQueue (/app/dist/jobs/queue.js:63:5)
> 
>     at async startServer (/app/dist/index.js:105:9) {
> 
>   length: 104,
> 
>   severity: 'FATAL',
> 
>   code: '28P01',
> 
>   detail: undefined,
> 
>   hint: undefined,
> 
>   position: undefined,
> 
>   internalPosition: undefined,
> 
>   internalQuery: undefined,
> 
>   where: undefined,
> 
>   schema: undefined,
> 
>   table: undefined,
> 
>   column: undefined,
> 
>   dataType: undefined,
> 
>   constraint: undefined,
> 
>   file: 'auth.c',
> 
>   line: '329',
> 
>   routine: 'auth_failed'
> 
> }
> ```
> 
> changed to Database container IP: 172.29.0.2 postgresql://postgres:postgres@172.29.0.2:5432/streamystats
> 
> After all that, still can not login

After updating I'm getting simmilar errors but about the embedding_base_url

ERROR:  column "embedding_base_url" does not exist at character 209
STATEMENT:  select "id", "name", "url", "api_key", "last_synced_playback_id", "local_address", "version", "product_name", "operating_system", "startup_wizard_completed", "auto_generate_embeddings", "embedding_provider", "embedding_base_url", "embedding_api_key", "embedding_model", "embedding_dimensions", "sync_status", "sync_progress", "sync_error", "last_sync_started", "last_sync_completed", "created_at", "updated_at" from "servers"

And stopping the stack and removing the volume and then recreating it from scratch I get the same errors as the user I quote.

Edit: By going to the server url I get error: "Internal Server Error" displayed instead of the interface.

**Comment by Hello-World-Traveler** [comment]
@Ciechom did you run streamystats-migrate to create database tables?

**Comment by iophobia** [comment]
Just chiming in that I have the same error after the upgrade to 2.6.0. Migration ran succesfully I presume. But on the login page, after I put in my JF credentials, I just see the "Logged in successfully" w/o any redirection. All I can see in the nextjs-app container logs is 
 ```
   ▲ Next.js 16.0.8
   - Local:         http://localhost:3000
   - Network:       http://0.0.0.0:3000
 ✓ Starting...
 ✓ Ready in 74ms
```
This is on Ubuntu 25.10 with Docker-CE 29.1.2 and a local IP without any proxy. It also didn't work in incognito mode. Will try other devices now as well.

**Comment by fredrikburmester** [comment]
Did you guys install via the 2.6.0 tag? In that case the nextjs server did not successfully build and i've had to manually rebuild that image. Can you see if you can update the stack again?

**Comment by iophobia** [comment]
I had the latest tag in my compose stack which if I'm not mistaken relates to the v2.6.0 image from ~3h ago anyway. Deleting and repulling the image didn't solve the problem in my case.

**Comment by fredrikburmester** [comment]
Are you all experiencing the same error? Fail to redirect after login? Have you all tried incognito browser? Eliminating old cookies may be present. 

What dose the developer console in chrome say?

**Comment by iophobia** [comment]
The dev console was the needed hint. Gives `Das Cookie "streamystats-session" wurde abgelehnt, weil ein Nicht-HTTPS-Cookie nicht als "secure" gesetzt werden kann.` upon login so probably assumes a HTTPS environment. So to check that I briefly exposed my streamystats install behind my reverse proxy and loading the dashboard worked again.

**Comment by fredrikburmester** [comment]
I've pushed an update to main, please wait for the build to finish and then you can see if it works. (if using :latest tag)

**Comment by Kyle-Mendes** [comment]
I just pulled the latest release of the `nextjs` container:

```
$ podman pull docker.io/fredrikburmester/streamystats-v2-nextjs:latest
Trying to pull docker.io/fredrikburmester/streamystats-v2-nextjs:latest...
Getting image source signatures
Copying blob 5818ca553db3 done   |
Copying blob fe07684b16b8 skipped: already exists
Copying blob 1b67613f0a72 skipped: already exists
Copying blob 508d5b721714 done   |
Copying blob c9ddb8507f84 skipped: already exists
Copying blob 1b662518c774 done   |
Copying blob f53d2425bfa5 done   |
Copying blob c1666690395a done   |
Copying blob dfb92eddc1a1 skipped: already exists
Copying blob 28a7a39bd780 done   |
Copying blob 61d495e78114 done   |
Copying config 24467da56a done   |
Writing manifest to image destination
24467da56ad3445e4b15df16e2f8a370e84a8a02e8ca6e7c2e09e9202150e775
```

I'm still getting the error though:

```
Error checking server connectivity: Error: Failed query: select "id", "name", "url", "api_key", "last_synced_playback_id>
params:
    at s.queryWithCache (.next/server/chunks/199.js:1:17780)
    at async (.next/server/chunks/199.js:19:15498)
    at async k (.next/server/chunks/2638.js:1:307)
    at async A (.next/server/app/api/check-connectivity/route.js:1:1965)
    at async k (.next/server/app/api/check-connectivity/route.js:1:5813)
    at async j (.next/server/app/api/check-connectivity/route.js:1:6822) {
  query: 'select "id", "name", "url", "api_key", "last_synced_playback_id", "local_address", "version", "product_name", >
  params: [],
  [cause]: Error: column "embedding_base_url" does not exist
      at ak (.next/server/chunks/199.js:6:2339)
      at <unknown> (.next/server/chunks/199.js:6:3385)
      at Socket.aN (.next/server/chunks/199.js:6:3389) {
    severity_local: 'ERROR',
    severity: 'ERROR',
    code: '42703',
    position: '209',
    file: 'parse_relation.c',
    line: '3716',
    routine: 'errorMissingColumn'
  }
}
```

I just get `internal server error` when trying to land on my streamystats page

--- 
EDIT: I did run the `migrations` again before this as well

**Comment by fredrikburmester** [comment]
That clearly shows that migrations did `not` run.

**Comment by Kyle-Mendes** [comment]
It seems like I had to manually pull the latest migrate docker image for some reason, although the others pulled.  Apologies :)

**Comment by Hello-World-Traveler** [comment]
@fredrikburmester Latest update fixed the issue, thank you.
