### ISSUE TITLE
Error streamystats-phoenix:edge

### ISSUE THREAD

**Issue by Druidblack** [fredrikburmester/streamystats#87]
Today (about an hour ago) I had a scheduled container upgrade. And now phoenix:edge won't start for me.

```
- 
- 17:57:09.011 [info] == Running 20250428183624 StreamystatServer.Repo.Migrations.AddPgvectorExtension.change/0 forward
- 
- 17:57:09.014 [info] execute "CREATE EXTENSION IF NOT EXISTS vector"
- 
- ** (Postgrex.Error) ERROR 0A000 (feature_not_supported) extension "vector" is not available
- 
-     hint: The extension must first be installed on the system where PostgreSQL is running.
- 
- Could not open extension control file "/usr/share/postgresql/16/extension/vector.control": No such file or directory.
- 
-     (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1096: Ecto.Adapters.SQL.raise_sql_call_error/1
- 
-     (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
- 
-     (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1203: Ecto.Adapters.SQL.execute_ddl/4
- 
-     (ecto_sql 3.12.1) lib/ecto/migration/runner.ex:348: Ecto.Migration.Runner.log_and_execute_ddl/3
- 
-     (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
- 
-     (ecto_sql 3.12.1) lib/ecto/migration/runner.ex:311: Ecto.Migration.Runner.perform_operation/3
- 
-     (stdlib 6.1.2) timer.erl:590: :timer.tc/2
- 
- 17:57:10.309 [notice] Application streamystat_server exited: exited in: StreamystatServer.Application.start(:normal, [])
- 
-     ** (EXIT) an exception was raised:
- 
-         ** (UndefinedFunctionError) function Mix.env/0 is undefined (module Mix is not available)
- 
-             Mix.env()
- 
-             (streamystat_server 1.7.1) lib/streamystat_server/application.ex:10: StreamystatServer.Application.start/2
- 
-             (kernel 10.1.1) application_master.erl:295: :application_master.start_it_old/4
- 
- {exit,terminating,[{application_controller,call,2,[{file,"application_controller.erl"},{line,511}]},{application,enqueue_or_start,6,[{file,"application.erl"},{line,380}]},{application,ensure_all_started,3,[{file,"application.erl"},{line,359}]},{elixir,start_cli,0,[{file,"src/elixir.erl"},{line,195}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}
- 
- Runtime terminating during boot (terminating)
- 
- Crash dump is being written to: erl_crash.dump...done
- 
- 18:00:35.643 [info] == Running 20250428183624 StreamystatServer.Repo.Migrations.AddPgvectorExtension.change/0 forward
- 
- 18:00:35.646 [info] execute "CREATE EXTENSION IF NOT EXISTS vector"
- 
- ** (Postgrex.Error) ERROR 0A000 (feature_not_supported) extension "vector" is not available
- 
-     hint: The extension must first be installed on the system where PostgreSQL is running.
- 
- Could not open extension control file "/usr/share/postgresql/16/extension/vector.control": No such file or directory.
- 
-     (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1096: Ecto.Adapters.SQL.raise_sql_call_error/1
- 
-     (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
- 
-     (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1203: Ecto.Adapters.SQL.execute_ddl/4
- 
-     (ecto_sql 3.12.1) lib/ecto/migration/runner.ex:348: Ecto.Migration.Runner.log_and_execute_ddl/3
- 
-     (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
- 
-     (ecto_sql 3.12.1) lib/ecto/migration/runner.ex:311: Ecto.Migration.Runner.perform_operation/3
- 
-     (stdlib 6.1.2) timer.erl:590: :timer.tc/2
- 
- 18:00:37.007 [notice] Application streamystat_server exited: exited in: StreamystatServer.Application.start(:normal, [])
- 
-     ** (EXIT) an exception was raised:
- 
-         ** (UndefinedFunctionError) function Mix.env/0 is undefined (module Mix is not available)
- 
-             Mix.env()
- 
-             (streamystat_server 1.7.1) lib/streamystat_server/application.ex:10: StreamystatServer.Application.start/2
- 
-             (kernel 10.1.1) application_master.erl:295: :application_master.start_it_old/4
- 
- {exit,terminating,[{application_controller,call,2,[{file,"application_controller.erl"},{line,511}]},{application,enqueue_or_start,6,[{file,"application.erl"},{line,380}]},{application,ensure_all_started,3,[{file,"application.erl"},{line,359}]},{elixir,start_cli,0,[{file,"src/elixir.erl"},{line,195}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}
- 
- Runtime terminating during boot (terminating)
- 
- Crash dump is being written to: erl_crash.dump...done
```

How can this be fixed?

**Comment by Druidblack** [comment]
Now I saw that the docker file has changed (the database image has been changed) I made all the edits when restarting the phoenix container: edge still shuts down with an error.
```
18:14:13.886 [info] Migrations already up

{exit,terminating,[{application_controller,call,2,[{file,"application_controller.erl"},{line,511}]},{application,enqueue_or_start,6,[{file,"application.erl"},{line,380}]},{application,ensure_all_started,3,[{file,"application.erl"},{line,359}]},{elixir,start_cli,0,[{file,"src/elixir.erl"},{line,195}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}

Runtime terminating during boot (terminating)

Crash dump is being written to: erl_crash.dump...done


```

**Comment by fairlanexD** [comment]
I also have the Same error!

**Comment by Druidblack** [comment]
Replaced the database image with tensorchord/pgvecto-rs:pg16-v0.3.0
When launching phoenix:edge, I get this error
```
19:55:31.287 [info] Migrations already up

{ex19:55:32.668 [notice] Application streamystat_server exited: exited in: StreamystatServer.Application.start(:normal, [])

    ** (EXIT) an exception was raised:

        ** (UndefinedFunctionError) function Mix.env/0 is undefined (module Mix is not available)

            Mix.env()

            (streamystat_server 1.7.1) lib/streamystat_server/application.ex:10: StreamystatServer.Application.start/2

            (kernel 10.1.1) application_master.erl:295: :application_master.start_it_old/4

Runtime terminating during boot (terminating)

it,terminating,[{application_controller,call,2,[{file,"application_controller.erl"},{line,511}]},{application,enqueue_or_start,6,[{file,"application.erl"},{line,380}]},{application,ensure_all_started,3,[{file,"application.erl"},{line,359}]},{elixir,start_cli,0,[{file,"src/elixir.erl"},{line,195}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}

Crash dump is being written to: erl_crash.dump...done

19:56:00.102 [info] Migrations already up

{exit,terminating,[{application_controller,call,2,[{file,"application_controller.erl"},{line,511}]},{application,enqueue_or_start,6,[{file,"application.erl"},{line,380}]},{application,ensure_all_started,3,[{file,"application.erl"},{line,359}]},{elixir,start_cli,0,[{file,"src/elixir.erl"},{line,195}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}

Runtime terminating during boot (terminating)

19:56:01.274 [notice] Application streamystat_server exited: exited in: StreamystatServer.Application.start(:normal, [])

    ** (EXIT) an exception was raised:

        ** (UndefinedFunctionError) function Mix.env/0 is undefined (module Mix is not available)

            Mix.env()

            (streamystat_server 1.7.1) lib/streamystat_server/application.ex:10: StreamystatServer.Application.start/2

            (kernel 10.1.1) application_master.erl:295: :application_master.start_it_old/4

Crash dump is being written to: erl_crash.dump...done
```

**Comment by mkarimdev** [comment]
iam also geting that
`    (stdlib 6.1.2) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
Last message: :poll_sessions
23:54:40.997 [error] GenServer StreamystatServer.Workers.SessionPoller terminating
** (Postgrex.Error) ERROR 42703 (undefined_column) column s0.open_ai_api_token does not exist
    query: SELECT s0."id", s0."url", s0."local_address", s0."server_name", s0."version", s0."product_name", s0."operating_system", s0."jellyfin_id", s0."startup_wizard_completed", s0."name", s0."api_key", s0."open_ai_api_token", s0."last_synced_playback_id", s0."inserted_at", s0."updated_at" FROM "servers" AS s0
    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1096: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:994: Ecto.Adapters.SQL.execute/6
    (ecto 3.12.4) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
    (ecto 3.12.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (streamystat_server 1.7.1) lib/streamystat_server/workers/session_poller.ex:57: StreamystatServer.Workers.SessionPoller.handle_info/2
    (stdlib 6.1.2) gen_server.erl:2345: :gen_server.try_handle_info/3
    (stdlib 6.1.2) gen_server.erl:2433: :gen_server.handle_msg/6
    (stdlib 6.1.2) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
Last message: :poll_sessions
23:54:51.000 [error] GenServer StreamystatServer.Workers.SessionPoller terminating
** (Postgrex.Error) ERROR 42703 (undefined_column) column s0.open_ai_api_token does not exist
    query: SELECT s0."id", s0."url", s0."local_address", s0."server_name", s0."version", s0."product_name", s0."operating_system", s0."jellyfin_id", s0."startup_wizard_completed", s0."name", s0."api_key", s0."open_ai_api_token", s0."last_synced_playback_id", s0."inserted_at", s0."updated_at" FROM "servers" AS s0
    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1096: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:994: Ecto.Adapters.SQL.execute/6
    (ecto 3.12.4) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
    (ecto 3.12.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (streamystat_server 1.7.1) lib/streamystat_server/workers/session_poller.ex:57: StreamystatServer.Workers.SessionPoller.handle_info/2
    (stdlib 6.1.2) gen_server.erl:2345: :gen_server.try_handle_info/3
    (stdlib 6.1.2) gen_server.erl:2433: :gen_server.handle_msg/6
    (stdlib 6.1.2) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
Last message: :poll_sessions
23:54:51.746 [notice] SIGTERM received - shutting down
Sat 17 May 2025 11:54:53 PM CEST - waiting for database to start
23:54:57.052 [info] == Running 20250428183624 StreamystatServer.Repo.Migrations.AddPgvectorExtension.change/0 forward
23:54:57.057 [info] execute "CREATE EXTENSION IF NOT EXISTS vectors"
** (Postgrex.Error) ERROR 0A000 (feature_not_supported) extension "vectors" is not available
    hint: The extension must first be installed on the system where PostgreSQL is running.
Could not open extension control file "/usr/share/postgresql/16/extension/vectors.control": No such file or directory.
    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1096: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1203: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.12.1) lib/ecto/migration/runner.ex:348: Ecto.Migration.Runner.log_and_execute_ddl/3
    (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.12.1) lib/ecto/migration/runner.ex:311: Ecto.Migration.Runner.perform_operation/3
    (stdlib 6.1.2) timer.erl:590: :timer.tc/2
23:54:59.164 [info] Running StreamystatServerWeb.Endpoint with Bandit 1.5.7 at :::4000 (http)
23:54:59.176 [info] Access StreamystatServerWeb.Endpoint at https://example.com
23:54:59.205 [error] Task #PID<0.2373.0> started from StreamystatServer.Supervisor terminating
** (Postgrex.Error) ERROR 42703 (undefined_column) column s0.open_ai_api_token does not exist
    query: SELECT s0."id", s0."url", s0."local_address", s0."server_name", s0."version", s0."product_name", s0."operating_system", s0."jellyfin_id", s0."startup_wizard_completed", s0."name", s0."api_key", s0."open_ai_api_token", s0."last_synced_playback_id", s0."inserted_at", s0."updated_at" FROM "servers" AS s0
    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1096: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:994: Ecto.Adapters.SQL.execute/6
    (ecto 3.12.4) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
    (ecto 3.12.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (streamystat_server 1.7.1) lib/streamystat_server/application.ex:40: StreamystatServer.Application.start_full_sync/0
    (elixir 1.17.3) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
Function: #Function<0.37063736/0 in StreamystatServer.Application.start_full_sync>

    Args: []
23:54:59.670 request_id=GEBvLjUj99OhEs8AAALC [info] GET /api/servers
23:54:59.672 request_id=GEBvLjUj99OhEs8AAALC [info] Sent 500 in 2ms
23:54:59.673 request_id=GEBvLjUj99OhEs8AAALC [error] ** (Postgrex.Error) ERROR 42703 (undefined_column) column s0.open_ai_api_token does not exist
    query: SELECT s0."id", s0."url", s0."local_address", s0."server_name", s0."version", s0."product_name", s0."operating_system", s0."jellyfin_id", s0."startup_wizard_completed", s0."name", s0."api_key", s0."open_ai_api_token", s0."last_synced_playback_id", s0."inserted_at", s0."updated_at" FROM "servers" AS s0
    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1096: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:994: Ecto.Adapters.SQL.execute/6
    (ecto 3.12.4) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
    (ecto 3.12.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (streamystat_server 1.7.1) lib/streamystat_server_web/controllers/server_controller.ex:6: StreamystatServerWeb.ServerController.index/2
    (streamystat_server 1.7.1) lib/streamystat_server_web/controllers/server_controller.ex:1: StreamystatServerWeb.ServerController.action/2
    (streamystat_server 1.7.1) lib/streamystat_server_web/controllers/server_controller.ex:1: StreamystatServerWeb.ServerController.phoenix_controller_pipeline/2
    (phoenix 1.7.14) lib/phoenix/router.ex:484: Phoenix.Router.__call__/5
23:54:59.869 request_id=GEBvLkD5n8ImFesAAALi [info] GET /api/servers
23:54:59.870 request_id=GEBvLkD5n8ImFesAAALi [info] Sent 500 in 1ms
23:54:59.871 request_id=GEBvLkD5n8ImFesAAALi [error] ** (Postgrex.Error) ERROR 42703 (undefined_column) column s0.open_ai_api_token does not exist
    query: SELECT s0."id", s0."url", s0."local_address", s0."server_name", s0."version", s0."product_name", s0."operating_system", s0."jellyfin_id", s0."startup_wizard_completed", s0."name", s0."api_key", s0."open_ai_api_token", s0."last_synced_playback_id", s0."inserted_at", s0."updated_at" FROM "servers" AS s0
    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1096: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:994: Ecto.Adapters.SQL.execute/6
    (ecto 3.12.4) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
    (ecto 3.12.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (streamystat_server 1.7.1) lib/streamystat_server_web/controllers/server_controller.ex:6: StreamystatServerWeb.ServerController.index/2
    (streamystat_server 1.7.1) lib/streamystat_server_web/controllers/server_controller.ex:1: StreamystatServerWeb.ServerController.action/2
    (streamystat_server 1.7.1) lib/streamystat_server_web/controllers/server_controller.ex:1: StreamystatServerWeb.ServerController.phoenix_controller_pipeline/2
    (phoenix 1.7.14) lib/phoenix/router.ex:484: Phoenix.Router.__call__/5
23:55:09.178 [error] GenServer StreamystatServer.Workers.SessionPoller terminating
** (Postgrex.Error) ERROR 42703 (undefined_column) column s0.open_ai_api_token does not exist
    query: SELECT s0."id", s0."url", s0."local_address", s0."server_name", s0."version", s0."product_name", s0."operating_system", s0."jellyfin_id", s0."startup_wizard_completed", s0."name", s0."api_key", s0."open_ai_api_token", s0."last_synced_playback_id", s0."inserted_at", s0."updated_at" FROM "servers" AS s0
    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1096: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:994: Ecto.Adapters.SQL.execute/6
    (ecto 3.12.4) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
    (ecto 3.12.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (streamystat_server 1.7.1) lib/streamystat_server/workers/session_poller.ex:57: StreamystatServer.Workers.SessionPoller.handle_info/2
    (stdlib 6.1.2) gen_server.erl:2345: :gen_server.try_handle_info/3
    (stdlib 6.1.2) gen_server.erl:2433: :gen_server.handle_msg/6
    (stdlib 6.1.2) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
Last message: :poll_sessions`

when i open the webui it askes to setup a new server

**Comment by mkarimdev** [comment]
Same here...
going back to [sha-e56bdb3](https://hub.docker.com/layers/fredrikburmester/streamystats-nextjs/sha-e56bdb3/images/sha256-dc04d077396d8eea850b986f97d56a83120b3c9c456766657410d7d310c54150) solves it temporarily

**Comment by fredrikburmester** [comment]
Have you guys also pulled the latest image? I think I fixed that issue.

**Comment by Panda260** [comment]
> Have you guys also pulled the latest image? I think I fixed that issue.

yes i have the latest version in a test setup and the error is still present

**Comment by Panda260** [comment]
it is working for me now

**Comment by Druidblack** [comment]
It's working for me now. but after all the changes. I don't see any statistics in the interface. I can see the browsing history at the same time.
When I switch to another server, I see the full view statistics window. How can this be fixed?

![Image](https://github.com/user-attachments/assets/824bc28e-3aef-4446-9ceb-cb0526d7407c)
![Image](https://github.com/user-attachments/assets/787bddc5-ee26-48cd-b830-1b7e248faa0e)

**Comment by fredrikburmester** [comment]
@Druidblack please check if you see any client or server side logs and open an issue if you do!

**Comment by fredrikburmester** [comment]
But i'll close this issue since the original issue is solved.
